(() => {
  const DEFAULT_LANGUAGE = 'vi';
  const LANGUAGES = [
    {code:'vi', name:'Tiếng Việt'},
    {code:'en', name:'English'},
    {code:'zh-CN', name:'简体中文'},
    {code:'zh-TW', name:'繁體中文'},
    {code:'ko', name:'한국어'},
    {code:'ja', name:'日本語'},
    {code:'th', name:'ไทย'},
    {code:'id', name:'Bahasa Indonesia'},
    {code:'es', name:'Español'},
    {code:'fr', name:'Français'}
  ];

  const vi = {
    appSubtitle:'Tải video Douyin chất lượng cao', checking:'Đang kiểm tra…', noTab:'Không tìm thấy tab hiện tại', notDouyin:'Hãy mở một trang video Douyin để sử dụng công cụ.', idle:'Sẵn sàng', capturing:'Đang bắt luồng', nativeReady:'Native Helper đã sẵn sàng', nativeMissing:'Chưa kết nối Native Helper', captureStart:'Bắt luồng', captureStop:'Dừng bắt', downloadBest:'Tải bản tốt nhất', tip:'Cho video chạy 2–3 giây để công cụ nhận đủ các luồng CDN và chọn bản tốt nhất.', streams:'Luồng phát hiện', noStreams:'Chưa phát hiện luồng video.', download:'Tải', best:'TỐT NHẤT', unknownSize:'Không rõ dung lượng', score:'điểm', language:'Ngôn ngữ', progress:'Tiến trình tải', preparing:'Đang chuẩn bị tải…', downloading:'Đang tải', completed:'Tải hoàn tất', failed:'Tải thất bại', downloaded:'Đã tải', speed:'Tốc độ', eta:'Còn lại', openFile:'Mở video', openFolder:'Mở thư mục', close:'Đóng', nativeMode:'Tải tốc độ cao', browserMode:'Tải bằng Chrome', seconds:'giây', readyToDownload:'Đã phát hiện {count} luồng', qualityUnknown:'Chất lượng chưa xác định', quickDownload:'↓ Tải HD', quickCapturing:'Đang bắt luồng…', analyzing:'Đang phân tích bản chất lượng cao nhất…', sentNative:'Đã gửi sang bộ tải tốc độ cao.', chromeFallback:'Đang tải bằng Chrome (chế độ dự phòng).', downloadProgress:'Đang tải {percent}% • {speed}', downloadComplete:'Tải xong: {filename}', downloadError:'Lỗi tải: {error}', cannotCapture:'Không thể bắt luồng', cannotDownload:'Không thể tải video', invalidPage:'Trang hiện tại không phải Douyin.', nativeHint:'Khuyên dùng Native Helper để tải ổn định và nhanh hơn.', version:'Phiên bản', sourceNetwork:'Mạng', sourcePage:'Trang', hls:'HLS', direct:'Trực tiếp', justNow:'Vừa xong', retry:'Thử lại', path:'Đường dẫn', copyPath:'Sao chép đường dẫn', copied:'Đã sao chép', bytesPerSecond:'MB/s'
  };

  const dict = {
    vi,
    en:{...vi, appSubtitle:'High-quality Douyin video downloader', checking:'Checking…', noTab:'No active tab found', notDouyin:'Open a Douyin video page to use this tool.', idle:'Ready', capturing:'Capturing streams', nativeReady:'Native Helper ready', nativeMissing:'Native Helper not connected', captureStart:'Capture', captureStop:'Stop capture', downloadBest:'Download best quality', tip:'Play the video for 2–3 seconds so the tool can detect CDN streams and choose the best one.', streams:'Detected streams', noStreams:'No video stream detected yet.', download:'Download', best:'BEST', unknownSize:'Unknown size', score:'score', language:'Language', progress:'Download progress', preparing:'Preparing download…', downloading:'Downloading', completed:'Download complete', failed:'Download failed', downloaded:'Downloaded', speed:'Speed', eta:'Time left', openFile:'Open video', openFolder:'Open folder', close:'Close', nativeMode:'High-speed native', browserMode:'Chrome fallback', seconds:'sec', readyToDownload:'Detected {count} streams', qualityUnknown:'Unknown quality', quickDownload:'↓ Download HD', quickCapturing:'Capturing…', analyzing:'Analyzing the highest-quality stream…', sentNative:'Sent to the high-speed downloader.', chromeFallback:'Downloading with Chrome fallback.', downloadProgress:'Downloading {percent}% • {speed}', downloadComplete:'Downloaded: {filename}', downloadError:'Download error: {error}', cannotCapture:'Unable to capture streams', cannotDownload:'Unable to download video', invalidPage:'The current page is not Douyin.', nativeHint:'Native Helper is recommended for faster and more reliable downloads.', version:'Version', sourceNetwork:'Network', sourcePage:'Page', hls:'HLS', direct:'Direct', justNow:'Done', retry:'Retry', path:'Path', copyPath:'Copy path', copied:'Copied'},
    'zh-CN':{...vi, appSubtitle:'高质量抖音视频下载器', checking:'正在检查…', noTab:'未找到当前标签页', notDouyin:'请打开抖音视频页面后使用此工具。', idle:'就绪', capturing:'正在捕获媒体流', nativeReady:'Native Helper 已就绪', nativeMissing:'Native Helper 未连接', captureStart:'捕获媒体流', captureStop:'停止捕获', downloadBest:'下载最高画质', tip:'让视频播放 2–3 秒，以便检测更多 CDN 流并选择最佳版本。', streams:'已检测媒体流', noStreams:'尚未检测到视频流。', download:'下载', best:'最佳', unknownSize:'大小未知', score:'评分', language:'语言', progress:'下载进度', preparing:'正在准备下载…', downloading:'正在下载', completed:'下载完成', failed:'下载失败', downloaded:'已下载', speed:'速度', eta:'剩余时间', openFile:'打开视频', openFolder:'打开文件夹', close:'关闭', nativeMode:'高速下载', browserMode:'Chrome 备用模式', seconds:'秒', readyToDownload:'已检测到 {count} 个媒体流', qualityUnknown:'画质未知', quickDownload:'↓ 下载 HD', quickCapturing:'正在捕获…', analyzing:'正在分析最高画质媒体流…', sentNative:'已发送到高速下载器。', chromeFallback:'正在使用 Chrome 备用模式下载。', downloadProgress:'正在下载 {percent}% • {speed}', downloadComplete:'下载完成：{filename}', downloadError:'下载错误：{error}', cannotCapture:'无法捕获媒体流', cannotDownload:'无法下载视频', invalidPage:'当前页面不是抖音。', nativeHint:'建议使用 Native Helper，以获得更快、更稳定的下载。', version:'版本', sourceNetwork:'网络', sourcePage:'页面', retry:'重试', path:'路径', copyPath:'复制路径', copied:'已复制'},
    'zh-TW':{...vi, appSubtitle:'高畫質抖音影片下載器', checking:'正在檢查…', noTab:'找不到目前分頁', notDouyin:'請開啟抖音影片頁面後使用此工具。', idle:'就緒', capturing:'正在擷取媒體串流', nativeReady:'Native Helper 已就緒', nativeMissing:'Native Helper 未連線', captureStart:'擷取串流', captureStop:'停止擷取', downloadBest:'下載最高畫質', tip:'讓影片播放 2–3 秒，以便偵測更多 CDN 串流並選擇最佳版本。', streams:'已偵測串流', noStreams:'尚未偵測到影片串流。', download:'下載', best:'最佳', unknownSize:'大小未知', score:'評分', language:'語言', progress:'下載進度', preparing:'正在準備下載…', downloading:'正在下載', completed:'下載完成', failed:'下載失敗', downloaded:'已下載', speed:'速度', eta:'剩餘時間', openFile:'開啟影片', openFolder:'開啟資料夾', close:'關閉', nativeMode:'高速下載', browserMode:'Chrome 備援模式', seconds:'秒', readyToDownload:'已偵測到 {count} 個串流', qualityUnknown:'畫質未知', quickDownload:'↓ 下載 HD', quickCapturing:'正在擷取…', analyzing:'正在分析最高畫質串流…', sentNative:'已送至高速下載器。', chromeFallback:'正在使用 Chrome 備援模式下載。', downloadProgress:'正在下載 {percent}% • {speed}', downloadComplete:'下載完成：{filename}', downloadError:'下載錯誤：{error}', cannotCapture:'無法擷取串流', cannotDownload:'無法下載影片', invalidPage:'目前頁面不是抖音。', nativeHint:'建議使用 Native Helper，以獲得更快、更穩定的下載。', version:'版本', sourceNetwork:'網路', sourcePage:'頁面', retry:'重試', path:'路徑', copyPath:'複製路徑', copied:'已複製'},
    ko:{...vi, appSubtitle:'고화질 Douyin 동영상 다운로더', checking:'확인 중…', noTab:'현재 탭을 찾을 수 없습니다', notDouyin:'Douyin 동영상 페이지를 열어 주세요.', idle:'준비됨', capturing:'스트림 감지 중', nativeReady:'Native Helper 준비됨', nativeMissing:'Native Helper 연결 안 됨', captureStart:'스트림 감지', captureStop:'감지 중지', downloadBest:'최고 화질 다운로드', tip:'영상 재생을 2–3초 유지하면 CDN 스트림을 더 많이 감지하여 최적 버전을 선택할 수 있습니다.', streams:'감지된 스트림', noStreams:'아직 동영상 스트림이 없습니다.', download:'다운로드', best:'최고', unknownSize:'용량 알 수 없음', score:'점수', language:'언어', progress:'다운로드 진행률', preparing:'다운로드 준비 중…', downloading:'다운로드 중', completed:'다운로드 완료', failed:'다운로드 실패', downloaded:'다운로드됨', speed:'속도', eta:'남은 시간', openFile:'동영상 열기', openFolder:'폴더 열기', close:'닫기', nativeMode:'고속 다운로드', browserMode:'Chrome 대체 모드', seconds:'초', readyToDownload:'{count}개 스트림 감지됨', qualityUnknown:'화질 정보 없음', quickDownload:'↓ HD 다운로드', quickCapturing:'스트림 감지 중…', analyzing:'최고 화질 스트림 분석 중…', sentNative:'고속 다운로더로 전송했습니다.', chromeFallback:'Chrome 대체 모드로 다운로드 중입니다.', downloadProgress:'다운로드 {percent}% • {speed}', downloadComplete:'다운로드 완료: {filename}', downloadError:'다운로드 오류: {error}', cannotCapture:'스트림을 감지할 수 없습니다', cannotDownload:'동영상을 다운로드할 수 없습니다', invalidPage:'현재 페이지는 Douyin이 아닙니다.', nativeHint:'더 빠르고 안정적인 다운로드를 위해 Native Helper를 권장합니다.', version:'버전', sourceNetwork:'네트워크', sourcePage:'페이지', retry:'다시 시도', path:'경로', copyPath:'경로 복사', copied:'복사됨'},
    ja:{...vi, appSubtitle:'高画質Douyin動画ダウンローダー', checking:'確認中…', noTab:'現在のタブが見つかりません', notDouyin:'Douyinの動画ページを開いてください。', idle:'準備完了', capturing:'ストリームを検出中', nativeReady:'Native Helper 準備完了', nativeMissing:'Native Helper 未接続', captureStart:'ストリーム検出', captureStop:'検出を停止', downloadBest:'最高画質をダウンロード', tip:'動画を2〜3秒再生すると、より多くのCDNストリームを検出して最適な版を選択できます。', streams:'検出したストリーム', noStreams:'動画ストリームはまだ検出されていません。', download:'ダウンロード', best:'最高', unknownSize:'サイズ不明', score:'スコア', language:'言語', progress:'ダウンロード進捗', preparing:'ダウンロード準備中…', downloading:'ダウンロード中', completed:'ダウンロード完了', failed:'ダウンロード失敗', downloaded:'ダウンロード済み', speed:'速度', eta:'残り時間', openFile:'動画を開く', openFolder:'フォルダーを開く', close:'閉じる', nativeMode:'高速ダウンロード', browserMode:'Chrome 代替モード', seconds:'秒', readyToDownload:'{count}件のストリームを検出', qualityUnknown:'画質不明', quickDownload:'↓ HDをダウンロード', quickCapturing:'検出中…', analyzing:'最高画質のストリームを解析中…', sentNative:'高速ダウンローダーに送信しました。', chromeFallback:'Chrome代替モードでダウンロード中です。', downloadProgress:'ダウンロード {percent}% • {speed}', downloadComplete:'ダウンロード完了: {filename}', downloadError:'ダウンロードエラー: {error}', cannotCapture:'ストリームを検出できません', cannotDownload:'動画をダウンロードできません', invalidPage:'現在のページはDouyinではありません。', nativeHint:'より高速で安定したダウンロードにはNative Helperを推奨します。', version:'バージョン', sourceNetwork:'ネットワーク', sourcePage:'ページ', retry:'再試行', path:'パス', copyPath:'パスをコピー', copied:'コピーしました'},
    th:{...vi, appSubtitle:'ตัวดาวน์โหลดวิดีโอ Douyin คุณภาพสูง', checking:'กำลังตรวจสอบ…', noTab:'ไม่พบแท็บปัจจุบัน', notDouyin:'โปรดเปิดหน้าวิดีโอ Douyin เพื่อใช้เครื่องมือนี้', idle:'พร้อมใช้งาน', capturing:'กำลังจับสตรีม', nativeReady:'Native Helper พร้อมใช้งาน', nativeMissing:'ยังไม่ได้เชื่อมต่อ Native Helper', captureStart:'จับสตรีม', captureStop:'หยุดจับ', downloadBest:'ดาวน์โหลดคุณภาพดีที่สุด', tip:'เล่นวิดีโอ 2–3 วินาที เพื่อให้ตรวจพบสตรีม CDN และเลือกเวอร์ชันที่ดีที่สุด', streams:'สตรีมที่ตรวจพบ', noStreams:'ยังไม่พบสตรีมวิดีโอ', download:'ดาวน์โหลด', best:'ดีที่สุด', unknownSize:'ไม่ทราบขนาด', score:'คะแนน', language:'ภาษา', progress:'ความคืบหน้าการดาวน์โหลด', preparing:'กำลังเตรียมดาวน์โหลด…', downloading:'กำลังดาวน์โหลด', completed:'ดาวน์โหลดเสร็จแล้ว', failed:'ดาวน์โหลดล้มเหลว', downloaded:'ดาวน์โหลดแล้ว', speed:'ความเร็ว', eta:'เวลาที่เหลือ', openFile:'เปิดวิดีโอ', openFolder:'เปิดโฟลเดอร์', close:'ปิด', nativeMode:'ดาวน์โหลดความเร็วสูง', browserMode:'โหมดสำรอง Chrome', seconds:'วินาที', readyToDownload:'พบ {count} สตรีม', qualityUnknown:'ไม่ทราบคุณภาพ', quickDownload:'↓ ดาวน์โหลด HD', quickCapturing:'กำลังจับสตรีม…', analyzing:'กำลังวิเคราะห์สตรีมคุณภาพสูงสุด…', sentNative:'ส่งไปยังตัวดาวน์โหลดความเร็วสูงแล้ว', chromeFallback:'กำลังดาวน์โหลดด้วยโหมดสำรอง Chrome', downloadProgress:'กำลังดาวน์โหลด {percent}% • {speed}', downloadComplete:'ดาวน์โหลดเสร็จ: {filename}', downloadError:'ข้อผิดพลาดการดาวน์โหลด: {error}', cannotCapture:'ไม่สามารถจับสตรีมได้', cannotDownload:'ไม่สามารถดาวน์โหลดวิดีโอได้', invalidPage:'หน้าปัจจุบันไม่ใช่ Douyin', nativeHint:'แนะนำ Native Helper เพื่อความเร็วและความเสถียรที่ดีกว่า', version:'เวอร์ชัน', sourceNetwork:'เครือข่าย', sourcePage:'หน้า', retry:'ลองอีกครั้ง', path:'พาธ', copyPath:'คัดลอกพาธ', copied:'คัดลอกแล้ว'},
    id:{...vi, appSubtitle:'Pengunduh video Douyin berkualitas tinggi', checking:'Memeriksa…', noTab:'Tab aktif tidak ditemukan', notDouyin:'Buka halaman video Douyin untuk menggunakan alat ini.', idle:'Siap', capturing:'Menangkap stream', nativeReady:'Native Helper siap', nativeMissing:'Native Helper belum terhubung', captureStart:'Tangkap stream', captureStop:'Hentikan', downloadBest:'Unduh kualitas terbaik', tip:'Putar video selama 2–3 detik agar alat mendeteksi lebih banyak stream CDN dan memilih versi terbaik.', streams:'Stream terdeteksi', noStreams:'Belum ada stream video yang terdeteksi.', download:'Unduh', best:'TERBAIK', unknownSize:'Ukuran tidak diketahui', score:'skor', language:'Bahasa', progress:'Progres unduhan', preparing:'Menyiapkan unduhan…', downloading:'Mengunduh', completed:'Unduhan selesai', failed:'Unduhan gagal', downloaded:'Terunduh', speed:'Kecepatan', eta:'Sisa waktu', openFile:'Buka video', openFolder:'Buka folder', close:'Tutup', nativeMode:'Unduhan cepat', browserMode:'Mode cadangan Chrome', seconds:'dtk', readyToDownload:'Terdeteksi {count} stream', qualityUnknown:'Kualitas tidak diketahui', quickDownload:'↓ Unduh HD', quickCapturing:'Menangkap stream…', analyzing:'Menganalisis stream kualitas tertinggi…', sentNative:'Dikirim ke pengunduh berkecepatan tinggi.', chromeFallback:'Mengunduh dengan mode cadangan Chrome.', downloadProgress:'Mengunduh {percent}% • {speed}', downloadComplete:'Selesai: {filename}', downloadError:'Kesalahan unduhan: {error}', cannotCapture:'Tidak dapat menangkap stream', cannotDownload:'Tidak dapat mengunduh video', invalidPage:'Halaman saat ini bukan Douyin.', nativeHint:'Native Helper disarankan untuk unduhan yang lebih cepat dan stabil.', version:'Versi', sourceNetwork:'Jaringan', sourcePage:'Halaman', retry:'Coba lagi', path:'Lokasi', copyPath:'Salin lokasi', copied:'Disalin'},
    es:{...vi, appSubtitle:'Descargador de vídeos Douyin en alta calidad', checking:'Comprobando…', noTab:'No se encontró la pestaña activa', notDouyin:'Abre una página de vídeo de Douyin para usar la herramienta.', idle:'Listo', capturing:'Capturando flujos', nativeReady:'Native Helper listo', nativeMissing:'Native Helper no conectado', captureStart:'Capturar flujos', captureStop:'Detener', downloadBest:'Descargar mejor calidad', tip:'Reproduce el vídeo durante 2–3 segundos para detectar más flujos CDN y elegir la mejor versión.', streams:'Flujos detectados', noStreams:'Aún no se detectaron flujos de vídeo.', download:'Descargar', best:'MEJOR', unknownSize:'Tamaño desconocido', score:'puntuación', language:'Idioma', progress:'Progreso de descarga', preparing:'Preparando descarga…', downloading:'Descargando', completed:'Descarga completada', failed:'Descarga fallida', downloaded:'Descargado', speed:'Velocidad', eta:'Tiempo restante', openFile:'Abrir vídeo', openFolder:'Abrir carpeta', close:'Cerrar', nativeMode:'Descarga rápida', browserMode:'Modo alternativo de Chrome', seconds:'s', readyToDownload:'Se detectaron {count} flujos', qualityUnknown:'Calidad desconocida', quickDownload:'↓ Descargar HD', quickCapturing:'Capturando…', analyzing:'Analizando el flujo de mayor calidad…', sentNative:'Enviado al descargador de alta velocidad.', chromeFallback:'Descargando con el modo alternativo de Chrome.', downloadProgress:'Descargando {percent}% • {speed}', downloadComplete:'Descargado: {filename}', downloadError:'Error de descarga: {error}', cannotCapture:'No se pueden capturar los flujos', cannotDownload:'No se puede descargar el vídeo', invalidPage:'La página actual no es Douyin.', nativeHint:'Se recomienda Native Helper para descargas más rápidas y fiables.', version:'Versión', sourceNetwork:'Red', sourcePage:'Página', retry:'Reintentar', path:'Ruta', copyPath:'Copiar ruta', copied:'Copiado'},
    fr:{...vi, appSubtitle:'Téléchargeur de vidéos Douyin en haute qualité', checking:'Vérification…', noTab:'Aucun onglet actif trouvé', notDouyin:'Ouvrez une page vidéo Douyin pour utiliser cet outil.', idle:'Prêt', capturing:'Capture des flux', nativeReady:'Native Helper prêt', nativeMissing:'Native Helper non connecté', captureStart:'Capturer les flux', captureStop:'Arrêter', downloadBest:'Télécharger la meilleure qualité', tip:'Laissez la vidéo jouer 2–3 secondes pour détecter davantage de flux CDN et choisir la meilleure version.', streams:'Flux détectés', noStreams:'Aucun flux vidéo détecté pour le moment.', download:'Télécharger', best:'MEILLEUR', unknownSize:'Taille inconnue', score:'score', language:'Langue', progress:'Progression du téléchargement', preparing:'Préparation du téléchargement…', downloading:'Téléchargement', completed:'Téléchargement terminé', failed:'Échec du téléchargement', downloaded:'Téléchargé', speed:'Vitesse', eta:'Temps restant', openFile:'Ouvrir la vidéo', openFolder:'Ouvrir le dossier', close:'Fermer', nativeMode:'Téléchargement rapide', browserMode:'Mode de secours Chrome', seconds:'s', readyToDownload:'{count} flux détectés', qualityUnknown:'Qualité inconnue', quickDownload:'↓ Télécharger HD', quickCapturing:'Capture en cours…', analyzing:'Analyse du flux de meilleure qualité…', sentNative:'Envoyé au téléchargeur haute vitesse.', chromeFallback:'Téléchargement via le mode de secours Chrome.', downloadProgress:'Téléchargement {percent}% • {speed}', downloadComplete:'Téléchargé : {filename}', downloadError:'Erreur de téléchargement : {error}', cannotCapture:'Impossible de capturer les flux', cannotDownload:'Impossible de télécharger la vidéo', invalidPage:'La page actuelle n’est pas Douyin.', nativeHint:'Native Helper est recommandé pour des téléchargements plus rapides et plus fiables.', version:'Version', sourceNetwork:'Réseau', sourcePage:'Page', retry:'Réessayer', path:'Chemin', copyPath:'Copier le chemin', copied:'Copié'}
  };

  function normalize(code) {
    if (!code) return DEFAULT_LANGUAGE;
    const raw = String(code).replace('_','-');
    if (dict[raw]) return raw;
    const lower = raw.toLowerCase();
    if (lower.startsWith('zh-tw') || lower.startsWith('zh-hk')) return 'zh-TW';
    if (lower.startsWith('zh')) return 'zh-CN';
    const base = lower.split('-')[0];
    return Object.keys(dict).find(k => k.toLowerCase() === base) || DEFAULT_LANGUAGE;
  }
  function format(text, vars={}) { return String(text).replace(/\{(\w+)\}/g, (_,k) => vars[k] ?? `{${k}}`); }
  function t(lang, key, vars={}) { const l=normalize(lang); return format(dict[l]?.[key] ?? dict.vi[key] ?? key, vars); }
  async function getLanguage() { try { const v=await chrome.storage.sync.get({language:DEFAULT_LANGUAGE}); return normalize(v.language); } catch { return DEFAULT_LANGUAGE; } }
  async function setLanguage(language) { const l=normalize(language); try { await chrome.storage.sync.set({language:l}); } catch {} return l; }
  window.DYHD_I18N = {DEFAULT_LANGUAGE, LANGUAGES, dict, normalize, t, getLanguage, setLanguage};
})();
