async function chooseFolder(){if(!state.nativeReady||state.nativeCompatible===false){showToast(t('saveFolderNativeHint'),true,4200);return}const r=await send({type:'CHOOSE_FOLDER',initialPath:saveFolder});if(r?.cancelled){showToast(t('folderChooseCancelled'));return}if(!r?.ok){showToast(r?.error||t('nativeFolderError'),true,4500);return}if(r.saveFolder){saveFolder=r.saveFolder;await chrome.storage.local.set({saveFolder});updateFolderUI();showToast(t('folderChosen'))}}

async function startDownload(candidateId=null,fromList=false,allowDuplicate=false){
  duplicateRecord=null;duplicateCandidateId=null;$('#duplicateCard').classList.add('hidden');const qualityMode=fromList?'best':$('#currentQuality').value||prefs.qualityMode;
  const r=await send({type:'DOWNLOAD',candidateId,qualityMode,allowDuplicate});if(!r?.ok){const info=friendlyError(r?.errorCode,r?.error);showToast(info.friendly,true,4500);state.download={type:'error',error:r?.error||'',errorCode:r?.errorCode||''};render();return}
  if(r.needsChoice){showToast(t('chooseQualityBelow'),false,3500);$('#list').scrollIntoView({behavior:'smooth',block:'nearest'});return}
  if(r.duplicate){duplicateRecord=r.record||null;duplicateCandidateId=candidateId||r.candidate?.id||null;renderDuplicate();if(r.skipped)showToast(t('duplicateSkipped'));return}
  state.download={type:'started',downloadId:r.downloadId,mode:r.mode,percent:0,bytes:0,total:r.candidate?.totalSize||r.candidate?.size||0,candidate:r.candidate,video:r.video};state.phase='downloading';render();showToast(r.mode==='native'?t('sentNative'):t('chromeFallback'))
}
function renderDuplicate(){const card=$('#duplicateCard');if(!duplicateRecord){card.classList.add('hidden');return}card.classList.remove('hidden');$('#duplicateMeta').textContent=`${duplicateRecord.filename||duplicateRecord.title||''} • ${fmtDate(duplicateRecord.completedAt)}`}
async function refreshDuplicateForCurrent(force=false){const key=state.video?.key||state.video?.videoId||'';if(!prefs.historyEnabled||!key){duplicateRecord=null;lastDuplicateVideoKey=key;renderDuplicate();return}if(!force&&key===lastDuplicateVideoKey)return;lastDuplicateVideoKey=key;const r=await send({type:'CHECK_DUPLICATE'});const currentKey=state.video?.key||state.video?.videoId||'';if(r?.ok&&r.videoKey===key&&currentKey===key){duplicateRecord=r.record||null;duplicateCandidateId=null;renderDuplicate()}}

async function runResultAction(type){const d=state.download;if(!d?.path&&!d?.browserId){showToast(t('pathUnavailable'),true);return}const btn=type==='OPEN_FILE'?$('#openFile'):$('#openFolder'),old=btn.textContent;btn.disabled=true;btn.textContent=t(type==='OPEN_FILE'?'openingFile':'openingFolder');const r=await send({type,path:d.path||'',downloadId:d.downloadId,mode:d.mode,browserId:d.browserId});btn.disabled=false;btn.textContent=old;if(!r?.ok)showToast(r?.error||t('actionFailed'),true,4200);else showToast(t(type==='OPEN_FILE'?'fileOpened':'folderOpened'))}
async function writeClipboard(text){try{await navigator.clipboard.writeText(text);return true}catch{}try{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();return !!ok}catch{return false}}
async function copyPath(){const text=state.download?.path||'';if(!text){showToast(t('pathUnavailable'),true);return}const ok=await writeClipboard(text);showToast(ok?t('copied'):t('clipboardFailed'),!ok)}

function showTab(name){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$$('.tab-panel').forEach(x=>x.classList.remove('active'));$(`#${name}Tab`)?.classList.add('active');if(name==='activity')refreshActivity();if(name==='settings'){populateSettingsControls(true);updateFolderUI()}}

async function refreshActivity(){const r=await send({type:'GET_ACTIVITY'});if(r?.ok){activity={active:r.active||[],history:r.history||[]};renderActivity()}}
function renderActivity(){
  const q=$('#queueList');q.innerHTML='';$('#activeCount').textContent=activity.active.length;if(!activity.active.length){q.innerHTML=`<div class="empty">${escapeHtml(t('queueEmpty'))}</div>`}else activity.active.forEach(d=>{const row=document.createElement('div');row.className='activity-item';const v=d.video||{},p=Math.max(0,Math.min(100,Number(d.percent)||0)),status=d.type==='queued'?t('queuedPosition',{position:d.queuePosition||1}):'';row.innerHTML=`<div class="activity-top"><img class="activity-thumb" src="${escapeHtml(v.thumbnail||'')}" alt=""><div class="activity-copy"><strong>${escapeHtml(v.title||d.filename||t('douyinVideo'))}</strong><small>${escapeHtml(v.author?('@'+v.author):'')} ${status?`• ${escapeHtml(status)}`:''} ${p?`• ${Math.round(p)}%`:''} ${d.speed?`• ${escapeHtml(d.speed)}`:''}</small></div></div><div class="activity-progress"><span style="width:${p}%"></span></div>`;q.appendChild(row)})
  const query=$('#historySearch').value.trim().toLowerCase(),h=$('#historyList');h.innerHTML='';const filtered=activity.history.filter(x=>!query||`${x.title} ${x.author} ${x.filename}`.toLowerCase().includes(query));if(!filtered.length){h.innerHTML=`<div class="empty">${escapeHtml(t('historyEmpty'))}</div>`;return}filtered.slice(0,200).forEach(item=>{const row=document.createElement('div');row.className='activity-item';row.innerHTML=`<div class="activity-top"><img class="activity-thumb" src="${escapeHtml(item.thumbnail||'')}" alt=""><div class="activity-copy"><strong>${escapeHtml(item.title||item.filename||t('douyinVideo'))}</strong><small>${escapeHtml(item.author?('@'+item.author):'')} • ${escapeHtml(fmtDate(item.completedAt))}${item.width&&item.height?` • ${item.width}×${item.height}`:''}${item.verified?` • ✓ ${escapeHtml(t('verifiedShort'))}`:''}</small></div></div><div class="activity-actions"><button class="btn tiny secondary" data-a="open">${escapeHtml(t('openFile'))}</button><button class="btn tiny secondary" data-a="folder">${escapeHtml(t('openFolder'))}</button><button class="btn tiny ghost" data-a="remove">${escapeHtml(t('removeHistory'))}</button></div>`;row.querySelector('[data-a="open"]').onclick=()=>historyAction(item.id,false);row.querySelector('[data-a="folder"]').onclick=()=>historyAction(item.id,true);row.querySelector('[data-a="remove"]').onclick=async()=>{await send({type:'DELETE_HISTORY',id:item.id});await refreshActivity()};h.appendChild(row)})
}
async function historyAction(id,folder){const r=await send({type:'HISTORY_OPEN',id,folder});showToast(r?.ok?t(folder?'folderOpened':'fileOpened'):(r?.error||t('actionFailed')),!r?.ok,4000)}

function renderDiagnostics(d){lastDiagnostics=d||null;const box=$('#diagnosticsBox'),copy=$('#copyDiagnosticsBtn');box.classList.remove('hidden');copy.classList.remove('hidden');const row=(label,value,ok)=>`<div class="diag-row"><span>${escapeHtml(label)}</span><span class="${ok===true?'diag-ok':ok===false?'diag-warn':''}">${escapeHtml(value)}</span></div>`;const nativeOk=!!d.nativeReady&&d.nativeCompatible!==false;box.innerHTML=row(t('diagNative'),!d.nativeReady?t('notReady'):nativeOk?`${t('ready')} · v${d.nativeVersion||'?'}`:t('nativeVersionMismatch',{version:d.nativeVersion||'?'}),nativeOk)+row(t('diagFolder'),d.saveFolder||'—',d.folderWritable)+row('FFmpeg',d.ffmpeg?d.ffmpegPath:t('notInstalled'),d.ffmpeg)+row('FFprobe',d.ffprobe?d.ffprobePath:t('notInstalled'),d.ffprobe)+row(t('diagDouyin'),d.isDouyin?t('ready'):t('notReady'),d.isDouyin)+row(t('diagStreams'),String(d.candidateCount||0),null)+row(t('diagQueue'),d.maxConcurrent?`${d.queueActive||0}/${d.maxConcurrent} · ${d.queueWaiting||0} ${t('waitingLower')}`:'—',null)}

async function exportPrefs(){const r=await send({type:'EXPORT_SETTINGS'});if(!r?.ok){showToast(r?.error||t('actionFailed'),true);return}const blob=new Blob([JSON.stringify(r.data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`douyin-hd-pro-settings-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast(t('exportDone'))}
async function importPrefsFile(file){try{const data=JSON.parse(await file.text());const r=await send({type:'IMPORT_SETTINGS',data});if(!r?.ok)throw new Error(r?.error||t('actionFailed'));await loadPrefs();lang=await DYHD_I18N.getLanguage();applyStaticText();populateSettingsControls(true);await refreshFolder();showToast(t('importDone'))}catch(e){showToast(`${t('importFailed')} ${e.message||''}`,true,5000)}}

function showSetup(){populateSetupFromPrefs();$('#appView').classList.add('hidden');$('#setupView').classList.remove('hidden')}
function showApp(){ $('#setupView').classList.add('hidden');$('#appView').classList.remove('hidden');render() }
function applyPresetDraft(name){const p=PRESET_DRAFTS[name]||PRESET_DRAFTS.personal;$('#setupAutoCapture').checked=p.autoCapture;fillQuality($('#setupQuality'),p.qualityMode);fillAfter($('#setupAfterDownload'),p.afterDownload);$('#setupHistory').checked=p.historyEnabled;$('#setupFilenameTemplate').value=p.filenameTemplate;$('#setupSubfolderTemplate').value=p.subfolderTemplate;const vm=$(`input[name="videoChangeMode"][value="${p.videoChangeMode}"]`);if(vm)vm.checked=true}
async function saveSetup(){const preset=$('input[name="preset"]:checked')?.value||'personal';lang=await DYHD_I18N.setLanguage($('#setupLanguage').value);const base=PRESET_DRAFTS[preset]||PRESET_DRAFTS.personal;const changes={...base,setupComplete:true,preset,autoCapture:$('#setupAutoCapture').checked,videoChangeMode:$('input[name="videoChangeMode"]:checked')?.value||'auto',qualityMode:$('#setupQuality').value,afterDownload:$('#setupAfterDownload').value,historyEnabled:$('#setupHistory').checked,filenameTemplate:$('#setupFilenameTemplate').value.trim()||'{author} - {title}',subfolderTemplate:$('#setupSubfolderTemplate').value.trim()};await persist(changes);fillLanguages($('#language'));showApp();showToast(t('settingsSaved'));if(prefs.autoCapture&&state.isDouyin&&!state.attached){const r=await send({type:'START_CAPTURE'});if(r?.ok)await refresh()}}

async function saveSetting(key,value){await persist({[key]:value});showToast(t('settingsSaved'),false,1200)}

$$('.tab').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
$('#language').onchange=async e=>{lang=await DYHD_I18N.setLanguage(e.target.value);applyStaticText();render();renderActivity()};
$('#capture').onclick=async()=>{const r=await send({type:state.attached?'STOP_CAPTURE':'START_CAPTURE'});if(!r?.ok)showToast(r?.error||t('cannotCapture'),true,4200);await refresh()};
$('#best').onclick=()=>startDownload(null,false,state.phase==='complete');$('#resetVideo').onclick=async()=>{const r=await send({type:'RESET_VIDEO',keepAttached:false});showToast(r?.ok?t('resetDone'):(r?.error||t('actionFailed')),!r?.ok);await refresh()};
$('#mainChooseFolder').onclick=chooseFolder;$('#chooseFolder').onclick=chooseFolder;$('#settingsChooseFolder').onclick=chooseFolder;$('#openFile').onclick=()=>runResultAction('OPEN_FILE');$('#openFolder').onclick=()=>runResultAction('OPEN_FOLDER');$('#copyPath').onclick=copyPath;
$('#currentQuality').onchange=async e=>{prefs.qualityMode=e.target.value;await chrome.storage.sync.set({qualityMode:prefs.qualityMode});fillQuality($('#settingQuality'),prefs.qualityMode)};
$('#duplicateDismiss').onclick=()=>{duplicateRecord=null;$('#duplicateCard').classList.add('hidden')};$('#duplicateOpen').onclick=async()=>{if(!duplicateRecord)return;const r=await send({type:'HISTORY_OPEN',id:duplicateRecord.id,folder:false});showToast(r?.ok?t('fileOpened'):(r?.error||t('actionFailed')),!r?.ok)};$('#duplicateAgain').onclick=()=>startDownload(duplicateCandidateId,false,true);
$('#historySearch').oninput=renderActivity;$('#clearHistory').onclick=async()=>{if(confirm(t('clearHistoryConfirm'))){await send({type:'CLEAR_HISTORY'});await refreshActivity();showToast(t('historyCleared'))}};
$('#diagnoseQuick').onclick=async()=>{showTab('settings');const r=await send({type:'GET_DIAGNOSTICS'});if(r?.ok)renderDiagnostics(r.diagnostics);else showToast(r?.error||t('actionFailed'),true,4200)};$('#diagnosticsBtn').onclick=async()=>{const r=await send({type:'GET_DIAGNOSTICS'});if(r?.ok)renderDiagnostics(r.diagnostics);else showToast(r?.error||t('actionFailed'),true)};$('#copyDiagnosticsBtn').onclick=async()=>{if(!lastDiagnostics)return;const report={app:'Douyin HD Pro',generatedAt:new Date().toISOString(),...lastDiagnostics};const ok=await writeClipboard(JSON.stringify(report,null,2));showToast(ok?t('diagnosticsCopied'):t('clipboardFailed'),!ok)};
$('#updateBtn').onclick=async()=>{const box=$('#updateBox');box.classList.remove('hidden');box.innerHTML=`<small>${escapeHtml(t('checkingUpdate'))}</small>`;const r=await send({type:'CHECK_UPDATE'});if(!r?.ok){box.innerHTML=`<strong>${escapeHtml(t('updateCheckFailed'))}</strong><small>${escapeHtml(r?.error||'')}</small>`;return}box.innerHTML=`<strong>${escapeHtml(r.available?t('updateAvailable',{version:r.latest}):t('upToDate',{version:r.current}))}</strong><small>${escapeHtml(r.available?t('updateAvailableHint'):t('upToDateHint'))}</small>${r.available?`<button class="btn small primary" id="openReleaseNow">${escapeHtml(t('viewRelease'))}</button>`:''}`;$('#openReleaseNow')?.addEventListener('click',()=>send({type:'OPEN_RELEASE',url:r.url}))};
$('#exportBtn').onclick=exportPrefs;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>{const f=e.target.files?.[0];if(f)importPrefsFile(f);e.target.value=''};
$('#resetSettings').onclick=async()=>{if(!confirm(t('resetSettingsConfirm')))return;const r=await send({type:'RESET_ALL_SETTINGS'});lang='vi';await loadPrefs();prefs.setupComplete=true;await chrome.storage.sync.set({setupComplete:true});saveFolder=r?.saveFolder||t('defaultFolder');if(r?.saveFolder)await chrome.storage.local.set({saveFolder});else await chrome.storage.local.remove('saveFolder');applyStaticText();populateSettingsControls(true);updateFolderUI();showToast(t('settingsReset'));};

$('#settingAutoCapture').onchange=e=>saveSetting('autoCapture',e.target.checked);$('#settingVideoChange').onchange=e=>saveSetting('videoChangeMode',e.target.value);$('#settingQuality').onchange=e=>{saveSetting('qualityMode',e.target.value);fillQuality($('#currentQuality'),e.target.value)};$('#settingDuplicate').onchange=e=>saveSetting('duplicatePolicy',e.target.value);$('#settingAfter').onchange=e=>saveSetting('afterDownload',e.target.value);$('#settingFloatVisibility').onchange=e=>saveSetting('floatingVisibility',e.target.value);$('#settingFloatSide').onchange=e=>saveSetting('floatingSide',e.target.value);$('#settingFloatVertical').onchange=e=>saveSetting('floatingVertical',e.target.value);$('#settingHistoryEnabled').onchange=e=>saveSetting('historyEnabled',e.target.checked);$('#settingHistoryLimit').onchange=e=>saveSetting('historyLimit',Math.max(20,Math.min(500,Number(e.target.value)||100)));$('#settingFilenameTemplate').onchange=e=>saveSetting('filenameTemplate',e.target.value.trim()||'{author} - {title}');$('#settingSubfolderTemplate').onchange=e=>saveSetting('subfolderTemplate',e.target.value.trim());

$$('input[name="preset"]').forEach(x=>x.onchange=()=>{if(x.checked)applyPresetDraft(x.value)});$('#setupLanguage').onchange=e=>{lang=DYHD_I18N.normalize(e.target.value);applyStaticText();populateSetupFromPrefs({...prefs,qualityMode:$('#setupQuality').value,afterDownload:$('#setupAfterDownload').value,autoCapture:$('#setupAutoCapture').checked,historyEnabled:$('#setupHistory').checked,filenameTemplate:$('#setupFilenameTemplate').value,subfolderTemplate:$('#setupSubfolderTemplate').value,videoChangeMode:$('input[name="videoChangeMode"]:checked')?.value||'auto',preset:$('input[name="preset"]:checked')?.value||'personal'});$('#setupLanguage').value=lang};$('#setupSave').onclick=saveSetup;$('#setupLater').onclick=()=>showApp();

chrome.runtime.onMessage.addListener(msg=>{
  if(msg.type==='STATE'&&(!msg.tabId||msg.tabId===tabId)){state={...state,attached:!!msg.attached,candidates:msg.candidates||[],nativeReady:!!msg.nativeReady,nativeCompatible:msg.nativeCompatible!==undefined?!!msg.nativeCompatible:state.nativeCompatible,nativeHello:msg.nativeHello||state.nativeHello,download:msg.download!==undefined?msg.download:state.download,phase:msg.phase||state.phase,video:msg.video||state.video,videoEvent:msg.videoEvent||'',lastError:msg.lastError||''};render();void refreshDuplicateForCurrent(false)}
  if(msg.type==='VIDEO_SESSION_EVENT'&&(!msg.tabId||msg.tabId===tabId)){state.videoEvent=msg.event||'';state.video=msg.video||state.video;duplicateRecord=null;$('#duplicateCard').classList.add('hidden');render();void refreshDuplicateForCurrent(true);showToast(msg.event==='new_manual'?t('manualCaptureRequired'):t('autoCaptureNewVideo'),false,2500)}
  if(msg.type==='NATIVE_EVENT'&&msg.event&&(!msg.tabId||msg.tabId===tabId)){state.download={...(state.download||{}),...msg.event};if(['queued','started','progress','verifying','merging'].includes(msg.event.type))state.phase='downloading';if(msg.event.type==='complete')state.phase='complete';if(msg.event.type==='error')state.phase='error';render()}
  if(msg.type==='ACTIVITY_UPDATED'||msg.type==='QUEUE_EVENT'){if($('#activityTab').classList.contains('active'))refreshActivity()}
  if(msg.type==='POST_DOWNLOAD_ACTION_ERROR'&&(!msg.tabId||msg.tabId===tabId))showToast(msg.error||t('actionFailed'),true,4500)
});

(async()=>{
  lang=await DYHD_I18N.getLanguage();await loadPrefs();if(!prefs.setupComplete)lang=await DYHD_I18N.setLanguage('vi');fillLanguages($('#language'));applyStaticText();populateSettingsControls(true);populateSetupFromPrefs();await refresh();if(!prefs.setupComplete)showSetup();else{showApp();if(prefs.autoCapture&&state.isDouyin&&!state.attached&&state.phase!=='complete'){const r=await send({type:'START_CAPTURE'});if(r?.ok)await refresh()}}
})();
