let tabId=null,lang='vi',toastTimer=null,lastAutoActionId=null,settingsMode=false;
let state={attached:false,candidates:[],nativeReady:false,isDouyin:false,download:null,awaitingNewVideo:false,videoKey:'',videoEvent:''};
let prefs={setupComplete:false,autoCapture:true,afterDownload:'ask',filenameMode:'author_title',videoChangeMode:'auto'};
let saveFolder='';
const $=s=>document.querySelector(s);
const t=(key,vars={})=>DYHD_I18N.t(lang,key,vars);
const fmtBytes=n=>{if(!Number(n))return t('unknownSize');const u=['B','KB','MB','GB'];let i=0,x=Number(n);while(x>=1024&&i<u.length-1){x/=1024;i++}return `${x.toFixed(i?1:0)} ${u[i]}`};
const fmtEta=n=>{n=Number(n);if(!Number.isFinite(n)||n<=0)return '—';if(n<60)return `${Math.ceil(n)} ${t('seconds')}`;const m=Math.floor(n/60),s=Math.ceil(n%60);return `${m}m ${s}s`};
const send=msg=>new Promise(resolve=>chrome.runtime.sendMessage({...msg,tabId},r=>{const e=chrome.runtime.lastError;resolve(e?{ok:false,error:e.message}:r)}));
function showToast(text,error=false,ms=2600){const el=$('#toast');clearTimeout(toastTimer);el.textContent=text;el.classList.toggle('error',!!error);el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),ms)}
async function loadPrefs(){const r=await chrome.storage.sync.get({setupComplete:false,autoCapture:true,afterDownload:'ask',filenameMode:'author_title',videoChangeMode:'auto'});prefs={setupComplete:!!r.setupComplete,autoCapture:r.autoCapture!==false,afterDownload:['ask','open_file','open_folder','none'].includes(r.afterDownload)?r.afterDownload:'ask',filenameMode:['author_title','title','date_title'].includes(r.filenameMode)?r.filenameMode:'author_title',videoChangeMode:['auto','manual'].includes(r.videoChangeMode)?r.videoChangeMode:'auto'}}
function populateLanguageSelect(el){el.innerHTML='';for(const l of DYHD_I18N.LANGUAGES){const o=document.createElement('option');o.value=l.code;o.textContent=l.name;el.appendChild(o)}el.value=lang}
function option(select,value,label){const o=document.createElement('option');o.value=value;o.textContent=label;select.appendChild(o)}
function populateSetup(){populateLanguageSelect($('#setupLanguage'));$('#setupLanguage').value=lang;$('#autoCapture').checked=!!prefs.autoCapture;const mode=document.querySelector(`input[name="videoChangeMode"][value="${prefs.videoChangeMode}"]`);if(mode)mode.checked=true;const a=$('#afterDownload');a.innerHTML='';option(a,'ask',t('afterAsk'));option(a,'open_file',t('afterOpenFile'));option(a,'open_folder',t('afterOpenFolder'));option(a,'none',t('afterNothing'));a.value=prefs.afterDownload;const f=$('#filenameMode');f.innerHTML='';option(f,'author_title',t('nameAuthorTitle'));option(f,'title',t('nameTitle'));option(f,'date_title',t('nameDateTitle'));f.value=prefs.filenameMode;updateFolderUI()}
function updateFolderUI(){const shown=saveFolder||'%USERPROFILE%\\Downloads\\DouyinHD';$('#saveFolderPath').textContent=shown;$('#mainSavePath').textContent=shown;$('#chooseFolder').disabled=!state.nativeReady;$('#mainChooseFolder').disabled=!state.nativeReady}
function applyStaticText(){document.documentElement.lang=lang;$('#subtitle').textContent=t('appSubtitle');$('#settingsBtn').title=t('settings');$('#settingsBtn').setAttribute('aria-label',t('settings'));$('#capture').textContent=state.attached?t('captureStop'):t('captureStart');$('#best').textContent=t('downloadBest');$('#tip').textContent=t('tip');$('#streamsLabel').textContent=t('streams');$('#progressLabel').textContent=t('progress');$('#downloadedLabel').textContent=t('downloaded');$('#speedLabel').textContent=t('speed');$('#etaLabel').textContent=t('eta');$('#openFile').textContent=t('openFile');$('#openFolder').textContent=t('openFolder');$('#copyPath').textContent=t('copyPath');$('#afterQuestion').textContent=t('whatNext');$('#setupEyebrow').textContent=t('setupEyebrow');$('#setupTitle').textContent=t('setupTitle');$('#setupDesc').textContent=t('setupDesc');$('#setupLanguageLabel').textContent=t('setupLanguage');$('#setupLanguageHint').textContent=t('setupLanguageHint');$('#saveFolderLabel').textContent=t('saveFolder');$('#saveFolderHint').textContent=t('saveFolderHint');$('#saveFolderPathLabel').textContent=t('saveFolderPathLabel');$('#chooseFolder').textContent=t('chooseFolder');$('#saveFolderNativeHint').textContent=t('saveFolderNativeHint');$('#videoChangeLabel').textContent=t('videoChangeLabel');$('#videoChangeHint').textContent=t('videoChangeHint');$('#videoModeAutoTitle').textContent=t('videoModeAutoTitle');$('#videoModeAutoDesc').textContent=t('videoModeAutoDesc');$('#videoModeManualTitle').textContent=t('videoModeManualTitle');$('#videoModeManualDesc').textContent=t('videoModeManualDesc');$('#behaviorLabel').textContent=t('behaviorLabel');$('#behaviorHint').textContent=t('behaviorHint');$('#autoCaptureLabel').textContent=t('autoCapture');$('#autoCaptureHint').textContent=t('autoCaptureHint');$('#afterDownloadLabel').textContent=t('afterDownload');$('#filenameLabel').textContent=t('filenameMode');$('#setupCancel').textContent=settingsMode?t('back'):t('later');$('#setupSave').textContent=t('saveAndStart');$('#setupBack').setAttribute('aria-label',t('back'));$('#sessionEyebrow').textContent=t('sessionEyebrow');$('#resetVideo').textContent=t('resetVideo');$('#mainSaveLabel').textContent=t('mainSaveLabel');$('#mainChooseFolder').textContent=t('changeFolder');updateFolderUI()}
function candidateLabel(c){if(c.width&&c.height)return `${c.width}×${c.height}`;if(c.quality)return String(c.quality).toUpperCase();return t('qualityUnknown')}
function renderDownload(d){const card=$('#progressCard');if(!d){card.classList.add('hidden');return}card.classList.remove('hidden');const pct=Number.isFinite(Number(d.percent))?Math.max(0,Math.min(100,Number(d.percent))):0;$('#progressBar').style.width=`${pct}%`;$('#progressPercent').textContent=d.type==='complete'?'100%':`${pct.toFixed(pct>=10?0:1)}%`;$('#downloadedValue').textContent=d.bytes?`${fmtBytes(d.bytes)}${d.total?` / ${fmtBytes(d.total)}`:''}`:'—';$('#speedValue').textContent=d.speed||(d.speedBps?`${(d.speedBps/1048576).toFixed(1)} MB/s`:'—');$('#etaValue').textContent=fmtEta(d.etaSeconds);let title=t('preparing');if(d.type==='progress'||d.type==='started')title=t('downloading');if(d.type==='complete')title=t('completed');if(d.type==='error')title=t('failed');$('#progressTitle').textContent=title;const done=d.type==='complete';$('#afterQuestion').classList.toggle('hidden',!done||prefs.afterDownload!=='ask');$('#resultActions').classList.toggle('hidden',!done);$('#filePath').classList.toggle('hidden',!done||!d.path);$('#filePath').textContent=d.path||'';if(done&&prefs.afterDownload==='ask'&&d.downloadId&&lastAutoActionId!==d.downloadId){lastAutoActionId=d.downloadId;showToast(t('completed'))}}
function renderSession(){let title=t('sessionReady'),hint=t('sessionReadyHint');if(state.awaitingNewVideo){title=t('sessionCompleted');hint=prefs.videoChangeMode==='auto'?t('sessionCompletedAuto'):t('sessionCompletedManual')}else if(state.videoEvent==='new_auto'){title=t('sessionNewAuto');hint=t('sessionNewAutoHint')}else if(state.videoEvent==='new_manual'){title=t('sessionNewManual');hint=t('sessionNewManualHint')}else if(state.attached){title=t('sessionCapturing');hint=t('sessionCapturingHint')}$('#sessionTitle').textContent=title;$('#sessionHint').textContent=hint}
function render(){applyStaticText();$('#nativeDot').classList.toggle('ok',!!state.nativeReady);$('#nativeText').textContent=state.nativeReady?t('nativeReady'):t('nativeMissing');$('#status').textContent=!state.isDouyin?t('idle'):(state.attached?t('capturing'):(state.candidates.length?t('readyToDownload',{count:state.candidates.length}):t('idle')));$('#pageWarning').classList.toggle('hidden',state.isDouyin);$('#pageWarning').textContent=t('notDouyin');$('#capture').disabled=!state.isDouyin;$('#best').disabled=!state.isDouyin||!state.candidates.length;$('#capture').textContent=state.attached?t('captureStop'):t('captureStart');$('#count').textContent=state.candidates.length;renderSession();const list=$('#list');list.innerHTML='';if(!state.candidates.length){const e=document.createElement('div');e.className='empty';e.textContent=t('noStreams');list.appendChild(e)}else state.candidates.slice(0,12).forEach((c,i)=>{const d=document.createElement('div');d.className='item'+(i===0?' best':'');const type=(c.mime||(/m3u8/i.test(c.url||'')?'HLS':'MP4')).replace('application/vnd.apple.','').replace('video/','').toUpperCase();const res=c.width&&c.height?`${c.width}×${c.height} • `:'';const br=c.bitrate?`${(c.bitrate/1000000).toFixed(1)} Mbps • `:'';d.innerHTML=`<div class="meta"><div class="name"><span>${type}</span>${i===0?`<span class="badge">${t('best')}</span>`:''}<span class="quality">${candidateLabel(c)}</span></div><div class="sub">${res}${br}${fmtBytes(c.totalSize||c.size)} • ${t('score')} ${c.score}</div></div><button>${t('download')}</button>`;d.querySelector('button').onclick=()=>startDownload(c.id);list.appendChild(d)});renderDownload(state.download)}
async function refresh(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});tabId=tab?.id||null;if(!tabId){$('#status').textContent=t('noTab');return}const r=await send({type:'GET_STATE'});if(r?.ok){state={attached:!!r.attached,candidates:r.candidates||[],nativeReady:!!r.nativeReady,isDouyin:!!r.isDouyin,download:r.download||null,awaitingNewVideo:!!r.awaitingNewVideo,videoKey:r.videoKey||'',videoEvent:r.videoEvent||''};render()}await refreshNativeSettings(false)}
async function refreshNativeSettings(showError=false){if(!state.nativeReady){const local=await chrome.storage.local.get({saveFolder:''});saveFolder=local.saveFolder||saveFolder;updateFolderUI();if(showError)showToast(t('nativeFolderError'),true,4200);return false}const r=await send({type:'GET_NATIVE_SETTINGS'});if(r?.ok&&r.saveFolder){saveFolder=r.saveFolder;await chrome.storage.local.set({saveFolder});updateFolderUI();return true}const local=await chrome.storage.local.get({saveFolder:''});saveFolder=local.saveFolder||saveFolder;updateFolderUI();if(showError)showToast(r?.error||t('nativeFolderError'),true,4200);return false}
async function chooseFolder(){if(!state.nativeReady){showToast(t('saveFolderNativeHint'),true,4000);return}const r=await send({type:'CHOOSE_FOLDER',initialPath:saveFolder});if(!r?.ok){if(r?.cancelled)showToast(t('folderChooseCancelled'));else showToast(r?.error||t('nativeFolderError'),true,4500);return}if(r.saveFolder){saveFolder=r.saveFolder;await chrome.storage.local.set({saveFolder});updateFolderUI();showToast(t('folderChosen'))}}
async function startDownload(candidateId=null){const r=await send({type:'DOWNLOAD',candidateId});if(!r?.ok){state.download={type:'error',error:r?.error||t('cannotDownload')};render();showToast(r?.error||t('cannotDownload'),true,4500);return}state.download={type:'started',downloadId:r.downloadId,mode:r.mode,percent:0,bytes:0,total:r.candidate?.totalSize||r.candidate?.size||0};render();showToast(r.mode==='native'?t('sentNative'):t('chromeFallback'))}
async function runResultAction(type){const isFile=type==='OPEN_FILE';const d=state.download;if(!d?.path&&!d?.browserId){showToast(t('pathUnavailable'),true);return}const btn=isFile?$('#openFile'):$('#openFolder');const old=btn.textContent;btn.disabled=true;btn.textContent=isFile?t('openingFile'):t('openingFolder');try{const r=await send({type,path:d.path||'',downloadId:d.downloadId,mode:d.mode,browserId:d.browserId});if(!r?.ok)throw new Error(r?.error||t('actionFailed'));showToast(isFile?t('fileOpened'):t('folderOpened'))}catch(e){showToast(e.message||t('actionFailed'),true,4500)}finally{btn.disabled=false;btn.textContent=old}}
async function copyPath(){const text=state.download?.path||'';if(!text){showToast(t('pathUnavailable'),true);return}let ok=false;try{await navigator.clipboard.writeText(text);ok=true}catch{}if(!ok){try{const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();ok=document.execCommand('copy');ta.remove()}catch{}}showToast(ok?t('copied'):t('clipboardFailed'),!ok)}
function showSetup(asSettings=false){settingsMode=asSettings;populateSetup();applyStaticText();$('#setupBack').classList.toggle('hidden',!asSettings);$('#appView').classList.add('hidden');$('#setupView').classList.remove('hidden')}
function showApp(){settingsMode=false;$('#setupView').classList.add('hidden');$('#appView').classList.remove('hidden');render()}
async function saveSetup(){lang=await DYHD_I18N.setLanguage($('#setupLanguage').value);prefs={setupComplete:true,autoCapture:$('#autoCapture').checked,afterDownload:$('#afterDownload').value,filenameMode:$('#filenameMode').value,videoChangeMode:document.querySelector('input[name="videoChangeMode"]:checked')?.value||'auto'};await chrome.storage.sync.set(prefs);populateLanguageSelect($('#language'));showApp();showToast(t('settingsSaved'));if(prefs.autoCapture&&state.isDouyin&&!state.attached){const r=await send({type:'START_CAPTURE'});if(r?.ok){await refresh();showToast(t('autoCaptureStarted'))}}}
$('#capture').onclick=async()=>{const r=await send({type:state.attached?'STOP_CAPTURE':'START_CAPTURE'});if(!r?.ok)showToast(r?.error||t('cannotCapture'),true,4500);await refresh()};
$('#best').onclick=()=>startDownload(null);$('#language').onchange=async e=>{lang=await DYHD_I18N.setLanguage(e.target.value);render()};$('#settingsBtn').onclick=()=>showSetup(true);$('#setupBack').onclick=showApp;$('#setupCancel').onclick=()=>{if(settingsMode||prefs.setupComplete)showApp();else showApp()};$('#setupSave').onclick=saveSetup;$('#setupLanguage').onchange=e=>{const draft={autoCapture:$('#autoCapture').checked,afterDownload:$('#afterDownload').value,filenameMode:$('#filenameMode').value,videoChangeMode:document.querySelector('input[name="videoChangeMode"]:checked')?.value||'auto'};lang=DYHD_I18N.normalize(e.target.value);applyStaticText();populateSetup();$('#setupLanguage').value=lang;$('#autoCapture').checked=draft.autoCapture;$('#afterDownload').value=draft.afterDownload;$('#filenameMode').value=draft.filenameMode;const m=document.querySelector(`input[name="videoChangeMode"][value="${draft.videoChangeMode}"]`);if(m)m.checked=true};$('#chooseFolder').onclick=chooseFolder;$('#mainChooseFolder').onclick=chooseFolder;$('#openFile').onclick=()=>runResultAction('OPEN_FILE');$('#openFolder').onclick=()=>runResultAction('OPEN_FOLDER');$('#copyPath').onclick=copyPath;$('#resetVideo').onclick=async()=>{const r=await send({type:'RESET_VIDEO'});if(!r?.ok)showToast(r?.error||t('actionFailed'),true,4200);else{showToast(t('resetDone'));await refresh()}};
chrome.runtime.onMessage.addListener(msg=>{if(msg.type==='POST_DOWNLOAD_ACTION_ERROR'&&(!msg.tabId||msg.tabId===tabId)){showToast(msg.error||t('actionFailed'),true,4500)}if(msg.type==='VIDEO_SESSION_EVENT'&&(!msg.tabId||msg.tabId===tabId)){state.videoEvent=msg.event||'';if(msg.event==='new_manual')showToast(t('manualCaptureRequired'),false,3000);if(msg.event==='new_auto')showToast(t('autoCaptureNewVideo'),false,2400)}if(msg.type==='STATE'&&(!msg.tabId||msg.tabId===tabId)){state.attached=!!msg.attached;state.candidates=msg.candidates||[];state.nativeReady=!!msg.nativeReady;if(typeof msg.isDouyin==='boolean')state.isDouyin=msg.isDouyin;if(msg.download!==undefined)state.download=msg.download;if(typeof msg.awaitingNewVideo==='boolean')state.awaitingNewVideo=msg.awaitingNewVideo;if(msg.videoKey!==undefined)state.videoKey=msg.videoKey;if(msg.videoEvent!==undefined)state.videoEvent=msg.videoEvent;render()}if(msg.type==='NATIVE_EVENT'&&msg.event&&['started','progress','complete','error'].includes(msg.event.type)&&(!msg.tabId||msg.tabId===tabId)){state.download={...(state.download||{}),...msg.event};render()}});
(async()=>{lang=await DYHD_I18N.getLanguage();await loadPrefs();if(!prefs.setupComplete)lang=await DYHD_I18N.setLanguage('vi');populateLanguageSelect($('#language'));applyStaticText();await refresh();if(!prefs.setupComplete)showSetup(false);else{showApp();if(prefs.autoCapture&&state.isDouyin&&!state.attached&&!state.awaitingNewVideo){const r=await send({type:'START_CAPTURE'});if(r?.ok){await refresh();showToast(t('autoCaptureStarted'),false,1800)}}}})();
